### ISSUE TITLE
Problem running in electron

### ISSUE THREAD

**Issue by rohanpai** [sindresorhus/shell-env#2]
shell-env works great in development mode for electron but I'm having troubles executing it in a built electron app. Any ideas?

```
Uncaught Exception:
/Users/rohanpai/dev/myapp/release/darwin-x64/myapp-darwin-x64/myapp.app/Contents/Resources/app/main.js:13074
          ({"NODE_ENV":"production"}) = shellEnv.sync();
          ^
SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Object.<anonymous> (/Users/rohanpai/dev/myapp/release/darwin-x64/myapp-darwin-x64/myapp.app/Contents/Resources/electron.asar/browser/init.js:183:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
```

Thanks for the great work!

**Comment by sindresorhus** [comment]
> ({"NODE_ENV":"production"}) = shellEnv.sync();

Uhm, what is this line trying to do?

Doesn't look related to `shell-env`.

**Comment by silverwind** [comment]
Clearly looks like an error in either your code or one of your dependencies. Reopen if you think otherwise.
